# The tfvars files act as placeholders to signify which environment variables to look for.

aws_region                = var.AWS_REGION

RAW_S3_BUCKET_PATH        = var.DEV_RAW_S3_BUCKET_PATH
PROCESSED_S3_BUCKET_NAME  = var.DEV_PROCESSED_S3_BUCKET_NAME
KINESIS_STREAM_NAME       = var.DEV_KINESIS_STREAM_NAME
REDSHIFT_CLUSTER_ID       = var.DEV_REDSHIFT_CLUSTER_ID
REDSHIFT_DB_NAME          = var.DEV_REDSHIFT_DB_NAME
REDSHIFT_MASTER_USERNAME  = var.DEV_REDSHIFT_MASTER_USERNAME
REDSHIFT_MASTER_PASSWORD  = var.DEV_REDSHIFT_MASTER_PASSWORD
