aws_region                = var.AWS_REGION

RAW_S3_BUCKET_PATH        = var.PROD_RAW_S3_BUCKET_PATH
PROCESSED_S3_BUCKET_NAME  = var.PROD_PROCESSED_S3_BUCKET_NAME
KINESIS_STREAM_NAME       = var.PROD_KINESIS_STREAM_NAME
REDSHIFT_CLUSTER_ID       = var.PROD_REDSHIFT_CLUSTER_ID
REDSHIFT_DB_NAME          = var.PROD_REDSHIFT_DB_NAME
REDSHIFT_MASTER_USERNAME  = var.PROD_REDSHIFT_MASTER_USERNAME
REDSHIFT_MASTER_PASSWORD  = var.PROD_REDSHIFT_MASTER_PASSWORD
