aws_region                = var.AWS_REGION

RAW_S3_BUCKET_PATH        = var.STAGING_RAW_S3_BUCKET_PATH
PROCESSED_S3_BUCKET_NAME  = var.STAGING_PROCESSED_S3_BUCKET_NAME
KINESIS_STREAM_NAME       = var.STAGING_KINESIS_STREAM_NAME
REDSHIFT_CLUSTER_ID       = var.STAGING_REDSHIFT_CLUSTER_ID
REDSHIFT_DB_NAME          = var.STAGING_REDSHIFT_DB_NAME
REDSHIFT_MASTER_USERNAME  = var.STAGING_REDSHIFT_MASTER_USERNAME
REDSHIFT_MASTER_PASSWORD  = var.STAGING_REDSHIFT_MASTER_PASSWORD
